-- Schema مرجع هایپر باتری ماهر
-- این فایل ساختار فعلی سایت را با brand_id عددی هماهنگ می‌کند.

create extension if not exists pgcrypto;

create table if not exists public.brands(
  id bigint generated by default as identity primary key,
  name text not null unique,
  logo_url text,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products(
  id uuid primary key default gen_random_uuid(),
  brand_id bigint references public.brands(id) on delete set null,
  brand text,
  name text not null,
  category text not null default 'خودرو',
  amperage text,
  price numeric,
  description text,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings(
  key text primary key,
  value text not null default ''
);

create table if not exists public.admin_users(
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

insert into public.site_settings(key,value) values
('phone','09351232343'),
('address','اسلامشهر، خیابان گلها، نبش البرز ۷'),
('google_maps','https://www.google.com/maps/search/?api=1&query=' || replace('اسلامشهر، خیابان گلها، نبش البرز ۷',' ','+')),
('neshan','https://neshan.org/'),
('balad','https://balad.ir/'),
('instagram',''),
('whatsapp',''),
('seo_title','باتری اسلامشهر | هایپر باتری ماهر'),
('seo_description','فروش تخصصی انواع باتری با نصب در اسلامشهر و حومه، با قیمت درب کارخانه.')
on conflict(key) do update set value = excluded.value;

insert into storage.buckets(id,name,public)
values ('product-images','product-images',true)
on conflict(id) do update set public = true;

alter table public.products enable row level security;
alter table public.brands enable row level security;
alter table public.site_settings enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "public active products" on public.products;
create policy "public active products" on public.products
for select using(active=true);

drop policy if exists "admins products" on public.products;
create policy "admins products" on public.products
for all to authenticated
using(exists(select 1 from public.admin_users where id=auth.uid()))
with check(exists(select 1 from public.admin_users where id=auth.uid()));

drop policy if exists "public active brands" on public.brands;
create policy "public active brands" on public.brands
for select using(active=true);

drop policy if exists "admins brands" on public.brands;
create policy "admins brands" on public.brands
for all to authenticated
using(exists(select 1 from public.admin_users where id=auth.uid()))
with check(exists(select 1 from public.admin_users where id=auth.uid()));

drop policy if exists "public settings" on public.site_settings;
create policy "public settings" on public.site_settings
for select using(true);

drop policy if exists "admins settings" on public.site_settings;
create policy "admins settings" on public.site_settings
for all to authenticated
using(exists(select 1 from public.admin_users where id=auth.uid()))
with check(exists(select 1 from public.admin_users where id=auth.uid()));

drop policy if exists "own admin row" on public.admin_users;
create policy "own admin row" on public.admin_users
for select to authenticated using(id=auth.uid());

drop policy if exists "public product images" on storage.objects;
create policy "public product images" on storage.objects
for select using(bucket_id='product-images');

drop policy if exists "admin upload product images" on storage.objects;
create policy "admin upload product images" on storage.objects
for insert to authenticated
with check(bucket_id='product-images' and exists(select 1 from public.admin_users where id=auth.uid()));

drop policy if exists "admin update product images" on storage.objects;
create policy "admin update product images" on storage.objects
for update to authenticated
using(bucket_id='product-images' and exists(select 1 from public.admin_users where id=auth.uid()))
with check(bucket_id='product-images' and exists(select 1 from public.admin_users where id=auth.uid()));

drop policy if exists "admin delete product images" on storage.objects;
create policy "admin delete product images" on storage.objects
for delete to authenticated
using(bucket_id='product-images' and exists(select 1 from public.admin_users where id=auth.uid()));
